// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: rift.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TunnelType int32

const (
	TunnelType_HTTP  TunnelType = 0
	TunnelType_HTTPS TunnelType = 1
	TunnelType_TLS   TunnelType = 2
	TunnelType_TCP   TunnelType = 3
	TunnelType_UDP   TunnelType = 4
)

// Enum value maps for TunnelType.
var (
	TunnelType_name = map[int32]string{
		0: "HTTP",
		1: "HTTPS",
		2: "TLS",
		3: "TCP",
		4: "UDP",
	}
	TunnelType_value = map[string]int32{
		"HTTP":  0,
		"HTTPS": 1,
		"TLS":   2,
		"TCP":   3,
		"UDP":   4,
	}
)

func (x TunnelType) Enum() *TunnelType {
	p := new(TunnelType)
	*p = x
	return p
}

func (x TunnelType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TunnelType) Descriptor() protoreflect.EnumDescriptor {
	return file_rift_proto_enumTypes[0].Descriptor()
}

func (TunnelType) Type() protoreflect.EnumType {
	return &file_rift_proto_enumTypes[0]
}

func (x TunnelType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TunnelType.Descriptor instead.
func (TunnelType) EnumDescriptor() ([]byte, []int) {
	return file_rift_proto_rawDescGZIP(), []int{0}
}

type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*Envelope_Hello
	//	*Envelope_AuthResp
	//	*Envelope_Bind
	//	*Envelope_BindResp
	//	*Envelope_Unbind
	//	*Envelope_Ping
	//	*Envelope_Pong
	//	*Envelope_Error
	//	*Envelope_Shutdown
	Msg           isEnvelope_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_rift_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_rift_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_rift_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetMsg() isEnvelope_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *Envelope) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Msg.(*Envelope_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *Envelope) GetAuthResp() *AuthResp {
	if x != nil {
		if x, ok := x.Msg.(*Envelope_AuthResp); ok {
			return x.AuthResp
		}
	}
	return nil
}

func (x *Envelope) GetBind() *BindTunnel {
	if x != nil {
		if x, ok := x.Msg.(*Envelope_Bind); ok {
			return x.Bind
		}
	}
	return nil
}

func (x *Envelope) GetBindResp() *BindResp {
	if x != nil {
		if x, ok := x.Msg.(*Envelope_BindResp); ok {
			return x.BindResp
		}
	}
	return nil
}

func (x *Envelope) GetUnbind() *Unbind {
	if x != nil {
		if x, ok := x.Msg.(*Envelope_Unbind); ok {
			return x.Unbind
		}
	}
	return nil
}

func (x *Envelope) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Msg.(*Envelope_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *Envelope) GetPong() *Pong {
	if x != nil {
		if x, ok := x.Msg.(*Envelope_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

func (x *Envelope) GetError() *ErrorMsg {
	if x != nil {
		if x, ok := x.Msg.(*Envelope_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *Envelope) GetShutdown() *ShutdownMsg {
	if x != nil {
		if x, ok := x.Msg.(*Envelope_Shutdown); ok {
			return x.Shutdown
		}
	}
	return nil
}

type isEnvelope_Msg interface {
	isEnvelope_Msg()
}

type Envelope_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"` // agent -> edge (first message on the control stream)
}

type Envelope_AuthResp struct {
	AuthResp *AuthResp `protobuf:"bytes,2,opt,name=auth_resp,json=authResp,proto3,oneof"` // edge  -> agent
}

type Envelope_Bind struct {
	Bind *BindTunnel `protobuf:"bytes,3,opt,name=bind,proto3,oneof"` // agent -> edge
}

type Envelope_BindResp struct {
	BindResp *BindResp `protobuf:"bytes,4,opt,name=bind_resp,json=bindResp,proto3,oneof"` // edge  -> agent
}

type Envelope_Unbind struct {
	Unbind *Unbind `protobuf:"bytes,5,opt,name=unbind,proto3,oneof"` // agent -> edge
}

type Envelope_Ping struct {
	Ping *Ping `protobuf:"bytes,6,opt,name=ping,proto3,oneof"` // both
}

type Envelope_Pong struct {
	Pong *Pong `protobuf:"bytes,7,opt,name=pong,proto3,oneof"` // both
}

type Envelope_Error struct {
	Error *ErrorMsg `protobuf:"bytes,8,opt,name=error,proto3,oneof"` // both
}

type Envelope_Shutdown struct {
	Shutdown *ShutdownMsg `protobuf:"bytes,9,opt,name=shutdown,proto3,oneof"` // edge  -> agent (drain)
}

func (*Envelope_Hello) isEnvelope_Msg() {}

func (*Envelope_AuthResp) isEnvelope_Msg() {}

func (*Envelope_Bind) isEnvelope_Msg() {}

func (*Envelope_BindResp) isEnvelope_Msg() {}

func (*Envelope_Unbind) isEnvelope_Msg() {}

func (*Envelope_Ping) isEnvelope_Msg() {}

func (*Envelope_Pong) isEnvelope_Msg() {}

func (*Envelope_Error) isEnvelope_Msg() {}

func (*Envelope_Shutdown) isEnvelope_Msg() {}

type Hello struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion string                 `protobuf:"bytes,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"` // "1"
	AgentVersion    string                 `protobuf:"bytes,2,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	Os              string                 `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"` // "darwin|linux|windows"
	Arch            string                 `protobuf:"bytes,4,opt,name=arch,proto3" json:"arch,omitempty"`
	ApiKey          string                 `protobuf:"bytes,5,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`             // rk_live_...
	RegionHint      string                 `protobuf:"bytes,6,opt,name=region_hint,json=regionHint,proto3" json:"region_hint,omitempty"` // "auto" or region code
	Features        []string               `protobuf:"bytes,7,rep,name=features,proto3" json:"features,omitempty"`                       // e.g. "udp","tcp","quic"
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_rift_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_rift_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_rift_proto_rawDescGZIP(), []int{1}
}

func (x *Hello) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *Hello) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *Hello) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *Hello) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *Hello) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *Hello) GetRegionHint() string {
	if x != nil {
		return x.RegionHint
	}
	return ""
}

func (x *Hello) GetFeatures() []string {
	if x != nil {
		return x.Features
	}
	return nil
}

type AuthResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Plan          string                 `protobuf:"bytes,3,opt,name=plan,proto3" json:"plan,omitempty"`                            // "free|pro|team|payg"
	SessionId     string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // server-assigned, for logs/inspector
	Error         *ErrorMsg              `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`                          // set when ok=false
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResp) Reset() {
	*x = AuthResp{}
	mi := &file_rift_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResp) ProtoMessage() {}

func (x *AuthResp) ProtoReflect() protoreflect.Message {
	mi := &file_rift_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResp.ProtoReflect.Descriptor instead.
func (*AuthResp) Descriptor() ([]byte, []int) {
	return file_rift_proto_rawDescGZIP(), []int{2}
}

func (x *AuthResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *AuthResp) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *AuthResp) GetPlan() string {
	if x != nil {
		return x.Plan
	}
	return ""
}

func (x *AuthResp) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AuthResp) GetError() *ErrorMsg {
	if x != nil {
		return x.Error
	}
	return nil
}

type BindTunnel struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ClientTunnelId string                 `protobuf:"bytes,1,opt,name=client_tunnel_id,json=clientTunnelId,proto3" json:"client_tunnel_id,omitempty"` // agent-chosen local id (unique per session)
	Type           TunnelType             `protobuf:"varint,2,opt,name=type,proto3,enum=rift.v1.TunnelType" json:"type,omitempty"`
	Subdomain      string                 `protobuf:"bytes,3,opt,name=subdomain,proto3" json:"subdomain,omitempty"`                                                                       // requested; empty => random
	CustomDomain   string                 `protobuf:"bytes,4,opt,name=custom_domain,json=customDomain,proto3" json:"custom_domain,omitempty"`                                             // optional, must be verified in the control plane
	RemotePort     uint32                 `protobuf:"varint,5,opt,name=remote_port,json=remotePort,proto3" json:"remote_port,omitempty"`                                                  // for TCP/UDP; 0 => ephemeral assigned
	Options        map[string]string      `protobuf:"bytes,6,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // e.g. "basic_auth","host_header","schemes"
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BindTunnel) Reset() {
	*x = BindTunnel{}
	mi := &file_rift_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindTunnel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindTunnel) ProtoMessage() {}

func (x *BindTunnel) ProtoReflect() protoreflect.Message {
	mi := &file_rift_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindTunnel.ProtoReflect.Descriptor instead.
func (*BindTunnel) Descriptor() ([]byte, []int) {
	return file_rift_proto_rawDescGZIP(), []int{3}
}

func (x *BindTunnel) GetClientTunnelId() string {
	if x != nil {
		return x.ClientTunnelId
	}
	return ""
}

func (x *BindTunnel) GetType() TunnelType {
	if x != nil {
		return x.Type
	}
	return TunnelType_HTTP
}

func (x *BindTunnel) GetSubdomain() string {
	if x != nil {
		return x.Subdomain
	}
	return ""
}

func (x *BindTunnel) GetCustomDomain() string {
	if x != nil {
		return x.CustomDomain
	}
	return ""
}

func (x *BindTunnel) GetRemotePort() uint32 {
	if x != nil {
		return x.RemotePort
	}
	return 0
}

func (x *BindTunnel) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type BindResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ClientTunnelId string                 `protobuf:"bytes,1,opt,name=client_tunnel_id,json=clientTunnelId,proto3" json:"client_tunnel_id,omitempty"`
	Ok             bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	PublicUrl      string                 `protobuf:"bytes,3,opt,name=public_url,json=publicUrl,proto3" json:"public_url,omitempty"` // https://abc.rift.sh  or  tcp://edge:2222
	AssignedHost   string                 `protobuf:"bytes,4,opt,name=assigned_host,json=assignedHost,proto3" json:"assigned_host,omitempty"`
	AssignedPort   uint32                 `protobuf:"varint,5,opt,name=assigned_port,json=assignedPort,proto3" json:"assigned_port,omitempty"`
	Error          *ErrorMsg              `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"` // set when ok=false
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BindResp) Reset() {
	*x = BindResp{}
	mi := &file_rift_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindResp) ProtoMessage() {}

func (x *BindResp) ProtoReflect() protoreflect.Message {
	mi := &file_rift_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindResp.ProtoReflect.Descriptor instead.
func (*BindResp) Descriptor() ([]byte, []int) {
	return file_rift_proto_rawDescGZIP(), []int{4}
}

func (x *BindResp) GetClientTunnelId() string {
	if x != nil {
		return x.ClientTunnelId
	}
	return ""
}

func (x *BindResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *BindResp) GetPublicUrl() string {
	if x != nil {
		return x.PublicUrl
	}
	return ""
}

func (x *BindResp) GetAssignedHost() string {
	if x != nil {
		return x.AssignedHost
	}
	return ""
}

func (x *BindResp) GetAssignedPort() uint32 {
	if x != nil {
		return x.AssignedPort
	}
	return 0
}

func (x *BindResp) GetError() *ErrorMsg {
	if x != nil {
		return x.Error
	}
	return nil
}

type Unbind struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ClientTunnelId string                 `protobuf:"bytes,1,opt,name=client_tunnel_id,json=clientTunnelId,proto3" json:"client_tunnel_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Unbind) Reset() {
	*x = Unbind{}
	mi := &file_rift_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Unbind) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Unbind) ProtoMessage() {}

func (x *Unbind) ProtoReflect() protoreflect.Message {
	mi := &file_rift_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Unbind.ProtoReflect.Descriptor instead.
func (*Unbind) Descriptor() ([]byte, []int) {
	return file_rift_proto_rawDescGZIP(), []int{5}
}

func (x *Unbind) GetClientTunnelId() string {
	if x != nil {
		return x.ClientTunnelId
	}
	return ""
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TsUnixMs      int64                  `protobuf:"varint,1,opt,name=ts_unix_ms,json=tsUnixMs,proto3" json:"ts_unix_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_rift_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_rift_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_rift_proto_rawDescGZIP(), []int{6}
}

func (x *Ping) GetTsUnixMs() int64 {
	if x != nil {
		return x.TsUnixMs
	}
	return 0
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TsUnixMs      int64                  `protobuf:"varint,1,opt,name=ts_unix_ms,json=tsUnixMs,proto3" json:"ts_unix_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_rift_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_rift_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_rift_proto_rawDescGZIP(), []int{7}
}

func (x *Pong) GetTsUnixMs() int64 {
	if x != nil {
		return x.TsUnixMs
	}
	return 0
}

type ShutdownMsg struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Reason              string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	DrainDeadlineUnixMs int64                  `protobuf:"varint,2,opt,name=drain_deadline_unix_ms,json=drainDeadlineUnixMs,proto3" json:"drain_deadline_unix_ms,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ShutdownMsg) Reset() {
	*x = ShutdownMsg{}
	mi := &file_rift_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownMsg) ProtoMessage() {}

func (x *ShutdownMsg) ProtoReflect() protoreflect.Message {
	mi := &file_rift_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownMsg.ProtoReflect.Descriptor instead.
func (*ShutdownMsg) Descriptor() ([]byte, []int) {
	return file_rift_proto_rawDescGZIP(), []int{8}
}

func (x *ShutdownMsg) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ShutdownMsg) GetDrainDeadlineUnixMs() int64 {
	if x != nil {
		return x.DrainDeadlineUnixMs
	}
	return 0
}

type ErrorMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"` // see plan/00-ARCHITECTURE.md section 8
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorMsg) Reset() {
	*x = ErrorMsg{}
	mi := &file_rift_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorMsg) ProtoMessage() {}

func (x *ErrorMsg) ProtoReflect() protoreflect.Message {
	mi := &file_rift_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorMsg.ProtoReflect.Descriptor instead.
func (*ErrorMsg) Descriptor() ([]byte, []int) {
	return file_rift_proto_rawDescGZIP(), []int{9}
}

func (x *ErrorMsg) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorMsg) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StreamInit struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ClientTunnelId string                 `protobuf:"bytes,1,opt,name=client_tunnel_id,json=clientTunnelId,proto3" json:"client_tunnel_id,omitempty"`                               // which tunnel this data stream serves
	RemoteAddr     string                 `protobuf:"bytes,2,opt,name=remote_addr,json=remoteAddr,proto3" json:"remote_addr,omitempty"`                                             // public client ip:port (for inspector/logs)
	Proto          string                 `protobuf:"bytes,3,opt,name=proto,proto3" json:"proto,omitempty"`                                                                         // "http|https|tcp|udp"
	Meta           map[string]string      `protobuf:"bytes,4,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // e.g. sni, alpn
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StreamInit) Reset() {
	*x = StreamInit{}
	mi := &file_rift_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamInit) ProtoMessage() {}

func (x *StreamInit) ProtoReflect() protoreflect.Message {
	mi := &file_rift_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamInit.ProtoReflect.Descriptor instead.
func (*StreamInit) Descriptor() ([]byte, []int) {
	return file_rift_proto_rawDescGZIP(), []int{10}
}

func (x *StreamInit) GetClientTunnelId() string {
	if x != nil {
		return x.ClientTunnelId
	}
	return ""
}

func (x *StreamInit) GetRemoteAddr() string {
	if x != nil {
		return x.RemoteAddr
	}
	return ""
}

func (x *StreamInit) GetProto() string {
	if x != nil {
		return x.Proto
	}
	return ""
}

func (x *StreamInit) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

var File_rift_proto protoreflect.FileDescriptor

const file_rift_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"rift.proto\x12\arift.v1\"\x9c\x03\n" +
	"\bEnvelope\x12&\n" +
	"\x05hello\x18\x01 \x01(\v2\x0e.rift.v1.HelloH\x00R\x05hello\x120\n" +
	"\tauth_resp\x18\x02 \x01(\v2\x11.rift.v1.AuthRespH\x00R\bauthResp\x12)\n" +
	"\x04bind\x18\x03 \x01(\v2\x13.rift.v1.BindTunnelH\x00R\x04bind\x120\n" +
	"\tbind_resp\x18\x04 \x01(\v2\x11.rift.v1.BindRespH\x00R\bbindResp\x12)\n" +
	"\x06unbind\x18\x05 \x01(\v2\x0f.rift.v1.UnbindH\x00R\x06unbind\x12#\n" +
	"\x04ping\x18\x06 \x01(\v2\r.rift.v1.PingH\x00R\x04ping\x12#\n" +
	"\x04pong\x18\a \x01(\v2\r.rift.v1.PongH\x00R\x04pong\x12)\n" +
	"\x05error\x18\b \x01(\v2\x11.rift.v1.ErrorMsgH\x00R\x05error\x122\n" +
	"\bshutdown\x18\t \x01(\v2\x14.rift.v1.ShutdownMsgH\x00R\bshutdownB\x05\n" +
	"\x03msg\"\xd1\x01\n" +
	"\x05Hello\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\tR\x0fprotocolVersion\x12#\n" +
	"\ragent_version\x18\x02 \x01(\tR\fagentVersion\x12\x0e\n" +
	"\x02os\x18\x03 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x04 \x01(\tR\x04arch\x12\x17\n" +
	"\aapi_key\x18\x05 \x01(\tR\x06apiKey\x12\x1f\n" +
	"\vregion_hint\x18\x06 \x01(\tR\n" +
	"regionHint\x12\x1a\n" +
	"\bfeatures\x18\a \x03(\tR\bfeatures\"\x95\x01\n" +
	"\bAuthResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x12\n" +
	"\x04plan\x18\x03 \x01(\tR\x04plan\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\x12'\n" +
	"\x05error\x18\x05 \x01(\v2\x11.rift.v1.ErrorMsgR\x05error\"\xbb\x02\n" +
	"\n" +
	"BindTunnel\x12(\n" +
	"\x10client_tunnel_id\x18\x01 \x01(\tR\x0eclientTunnelId\x12'\n" +
	"\x04type\x18\x02 \x01(\x0e2\x13.rift.v1.TunnelTypeR\x04type\x12\x1c\n" +
	"\tsubdomain\x18\x03 \x01(\tR\tsubdomain\x12#\n" +
	"\rcustom_domain\x18\x04 \x01(\tR\fcustomDomain\x12\x1f\n" +
	"\vremote_port\x18\x05 \x01(\rR\n" +
	"remotePort\x12:\n" +
	"\aoptions\x18\x06 \x03(\v2 .rift.v1.BindTunnel.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd6\x01\n" +
	"\bBindResp\x12(\n" +
	"\x10client_tunnel_id\x18\x01 \x01(\tR\x0eclientTunnelId\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12\x1d\n" +
	"\n" +
	"public_url\x18\x03 \x01(\tR\tpublicUrl\x12#\n" +
	"\rassigned_host\x18\x04 \x01(\tR\fassignedHost\x12#\n" +
	"\rassigned_port\x18\x05 \x01(\rR\fassignedPort\x12'\n" +
	"\x05error\x18\x06 \x01(\v2\x11.rift.v1.ErrorMsgR\x05error\"2\n" +
	"\x06Unbind\x12(\n" +
	"\x10client_tunnel_id\x18\x01 \x01(\tR\x0eclientTunnelId\"$\n" +
	"\x04Ping\x12\x1c\n" +
	"\n" +
	"ts_unix_ms\x18\x01 \x01(\x03R\btsUnixMs\"$\n" +
	"\x04Pong\x12\x1c\n" +
	"\n" +
	"ts_unix_ms\x18\x01 \x01(\x03R\btsUnixMs\"Z\n" +
	"\vShutdownMsg\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\x123\n" +
	"\x16drain_deadline_unix_ms\x18\x02 \x01(\x03R\x13drainDeadlineUnixMs\"8\n" +
	"\bErrorMsg\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xd9\x01\n" +
	"\n" +
	"StreamInit\x12(\n" +
	"\x10client_tunnel_id\x18\x01 \x01(\tR\x0eclientTunnelId\x12\x1f\n" +
	"\vremote_addr\x18\x02 \x01(\tR\n" +
	"remoteAddr\x12\x14\n" +
	"\x05proto\x18\x03 \x01(\tR\x05proto\x121\n" +
	"\x04meta\x18\x04 \x03(\v2\x1d.rift.v1.StreamInit.MetaEntryR\x04meta\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*<\n" +
	"\n" +
	"TunnelType\x12\b\n" +
	"\x04HTTP\x10\x00\x12\t\n" +
	"\x05HTTPS\x10\x01\x12\a\n" +
	"\x03TLS\x10\x02\x12\a\n" +
	"\x03TCP\x10\x03\x12\a\n" +
	"\x03UDP\x10\x04B&Z$github.com/rift/rift/pkg/proto;protob\x06proto3"

var (
	file_rift_proto_rawDescOnce sync.Once
	file_rift_proto_rawDescData []byte
)

func file_rift_proto_rawDescGZIP() []byte {
	file_rift_proto_rawDescOnce.Do(func() {
		file_rift_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rift_proto_rawDesc), len(file_rift_proto_rawDesc)))
	})
	return file_rift_proto_rawDescData
}

var file_rift_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rift_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_rift_proto_goTypes = []any{
	(TunnelType)(0),     // 0: rift.v1.TunnelType
	(*Envelope)(nil),    // 1: rift.v1.Envelope
	(*Hello)(nil),       // 2: rift.v1.Hello
	(*AuthResp)(nil),    // 3: rift.v1.AuthResp
	(*BindTunnel)(nil),  // 4: rift.v1.BindTunnel
	(*BindResp)(nil),    // 5: rift.v1.BindResp
	(*Unbind)(nil),      // 6: rift.v1.Unbind
	(*Ping)(nil),        // 7: rift.v1.Ping
	(*Pong)(nil),        // 8: rift.v1.Pong
	(*ShutdownMsg)(nil), // 9: rift.v1.ShutdownMsg
	(*ErrorMsg)(nil),    // 10: rift.v1.ErrorMsg
	(*StreamInit)(nil),  // 11: rift.v1.StreamInit
	nil,                 // 12: rift.v1.BindTunnel.OptionsEntry
	nil,                 // 13: rift.v1.StreamInit.MetaEntry
}
var file_rift_proto_depIdxs = []int32{
	2,  // 0: rift.v1.Envelope.hello:type_name -> rift.v1.Hello
	3,  // 1: rift.v1.Envelope.auth_resp:type_name -> rift.v1.AuthResp
	4,  // 2: rift.v1.Envelope.bind:type_name -> rift.v1.BindTunnel
	5,  // 3: rift.v1.Envelope.bind_resp:type_name -> rift.v1.BindResp
	6,  // 4: rift.v1.Envelope.unbind:type_name -> rift.v1.Unbind
	7,  // 5: rift.v1.Envelope.ping:type_name -> rift.v1.Ping
	8,  // 6: rift.v1.Envelope.pong:type_name -> rift.v1.Pong
	10, // 7: rift.v1.Envelope.error:type_name -> rift.v1.ErrorMsg
	9,  // 8: rift.v1.Envelope.shutdown:type_name -> rift.v1.ShutdownMsg
	10, // 9: rift.v1.AuthResp.error:type_name -> rift.v1.ErrorMsg
	0,  // 10: rift.v1.BindTunnel.type:type_name -> rift.v1.TunnelType
	12, // 11: rift.v1.BindTunnel.options:type_name -> rift.v1.BindTunnel.OptionsEntry
	10, // 12: rift.v1.BindResp.error:type_name -> rift.v1.ErrorMsg
	13, // 13: rift.v1.StreamInit.meta:type_name -> rift.v1.StreamInit.MetaEntry
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_rift_proto_init() }
func file_rift_proto_init() {
	if File_rift_proto != nil {
		return
	}
	file_rift_proto_msgTypes[0].OneofWrappers = []any{
		(*Envelope_Hello)(nil),
		(*Envelope_AuthResp)(nil),
		(*Envelope_Bind)(nil),
		(*Envelope_BindResp)(nil),
		(*Envelope_Unbind)(nil),
		(*Envelope_Ping)(nil),
		(*Envelope_Pong)(nil),
		(*Envelope_Error)(nil),
		(*Envelope_Shutdown)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rift_proto_rawDesc), len(file_rift_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rift_proto_goTypes,
		DependencyIndexes: file_rift_proto_depIdxs,
		EnumInfos:         file_rift_proto_enumTypes,
		MessageInfos:      file_rift_proto_msgTypes,
	}.Build()
	File_rift_proto = out.File
	file_rift_proto_goTypes = nil
	file_rift_proto_depIdxs = nil
}
