{{- if and .Values.api.enabled .Values.api.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "trqsh.fullname" . }}-api
  labels:
    {{- include "trqsh.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  minAvailable: {{ .Values.api.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "trqsh.selectorLabels" (dict "root" . "component" "api") | nindent 6 }}
{{- end }}
